// AirborneObject.java (Updated for Object Trails)

import java.awt.*;
import java.awt.geom.Point2D; // NEW: To store double-precision points for trail
import java.util.Random;
import java.util.LinkedList;    // NEW: For the trail history

// The AirborneObject class represents a single aerial object on the radar display.
class AirborneObject {

    // --- Private Fields ---
    private double x, y; // Current position of the object (top-left corner of its bounding box).
    private double dx, dy; // Direction and speed of the object (change in x and y per update).
    private int size; // Size of the object (represented as a square).
    private Color color; // Color of the object on the display.
    private boolean currentlyDetectedByBeam; // Flag if object is currently being hit by the radar beam.
    private int altitude; // Altitude of the object in meters.
    private String objectID; // Unique identifier for the object.

    private Random random; // Random number generator for initial placement and movement changes.

    // NEW: Fields for Object Trails
    private LinkedList<Point2D.Double> trail; // Stores history of positions for the trail
    public static final int MAX_TRAIL_LENGTH = 30; // Number of points in the trail (for approx 0.6 seconds trail)


    // --- Constructor ---
    // Initializes a new AirborneObject object with a random position, speed, and altitude.
    // 'panelWidth' and 'panelHeight' are needed to spawn objects off-screen.
    public AirborneObject(int panelWidth, int panelHeight) {
        random = new Random();
        size = 10; // Objects will be drawn as 10x10 pixel squares.
        color = Color.RED; // Default color is red.
        currentlyDetectedByBeam = false; // Initially, not detected by beam.

        this.objectID = "OBJ-" + (1000 + random.nextInt(9000)); // Generates IDs like OBJ-1000 to OBJ-9999

        this.altitude = 20 + random.nextInt(481); // Altitude between 20 and 500 meters

        // Object speed in pixels per frame.
        double baseSpeed = 1.0 + (1.5 * random.nextDouble()); // Random speed between 1.0 and 2.5 pixels/frame

        // Determine starting position and initial direction (off-screen, moving inwards).
        int edge = random.nextInt(4); // 0: top, 1: right, 2: bottom, 3: left

        switch (edge) {
            case 0: // Top edge
                x = random.nextDouble() * panelWidth;
                y = -size; // Spawns just off the top edge
                dx = (random.nextBoolean() ? 1 : -1) * (random.nextDouble() * baseSpeed * 0.5); // Slower horizontal drift
                dy = baseSpeed; // Moves downwards
                break;
            case 1: // Right edge
                x = panelWidth; // Spawns just off the right edge
                y = random.nextDouble() * panelHeight;
                dx = -baseSpeed; // Moves leftwards
                dy = (random.nextBoolean() ? 1 : -1) * (random.nextDouble() * baseSpeed * 0.5); // Slower vertical drift
                break;
            case 2: // Bottom edge
                x = random.nextDouble() * panelWidth;
                y = panelHeight; // Spawns just off the bottom edge
                dx = (random.nextBoolean() ? 1 : -1) * (random.nextDouble() * baseSpeed * 0.5);
                dy = -baseSpeed; // Moves upwards
                break;
            case 3: // Left edge
                x = -size; // Spawns just off the left edge
                y = random.nextDouble() * panelHeight;
                dx = baseSpeed; // Moves rightwards
                dy = (random.nextBoolean() ? 1 : -1) * (random.nextDouble() * baseSpeed * 0.5);
                break;
        }

        // NEW: Initialize the trail list and add the initial position
        this.trail = new LinkedList<>();
        this.trail.add(new Point2D.Double(x, y));
    }

    // --- Methods ---

    // Updates the object's position.
    public void move(int panelWidth, int panelHeight) {
        x += dx;
        y += dy;
        // Bouncing logic removed, objects will move off-screen and be re-generated by RadarPanel.

        // NEW: Update trail history
        trail.addFirst(new Point2D.Double(x, y)); // Add current position to the front (newest)
        if (trail.size() > MAX_TRAIL_LENGTH) {
            trail.removeLast(); // Remove the oldest position if the trail exceeds max length
        }
    }

    // Draws the object on the given Graphics2D context.
    public void draw(Graphics2D g2d) {
        g2d.setColor(currentlyDetectedByBeam ? Color.YELLOW : Color.RED);
        g2d.fillRect((int) x, (int) y, size, size);
        g2d.setColor(Color.BLACK);
        g2d.drawRect((int) x, (int) y, size, size);
    }

    // --- Getters and Setters ---
    public double getX() { return x; }
    public double getY() { return y; }
    public int getSize() { return size; }
    public boolean isCurrentlyDetectedByBeam() { return currentlyDetectedByBeam; }
    public void setCurrentlyDetectedByBeam(boolean detected) { this.currentlyDetectedByBeam = detected; }
    public int getAltitude() { return altitude; }
    public String getObjectID() { return objectID; }

    // NEW: Getter for the object's trail
    public LinkedList<Point2D.Double> getTrail() {
        return trail;
    }
}